// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: message-schema.proto

package messageschema

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ExecuteMode int32

const (
	ExecuteMode_Asynchronous ExecuteMode = 0
	ExecuteMode_Synchronous  ExecuteMode = 1
)

// Enum value maps for ExecuteMode.
var (
	ExecuteMode_name = map[int32]string{
		0: "Asynchronous",
		1: "Synchronous",
	}
	ExecuteMode_value = map[string]int32{
		"Asynchronous": 0,
		"Synchronous":  1,
	}
)

func (x ExecuteMode) Enum() *ExecuteMode {
	p := new(ExecuteMode)
	*p = x
	return p
}

func (x ExecuteMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecuteMode) Descriptor() protoreflect.EnumDescriptor {
	return file_message_schema_proto_enumTypes[0].Descriptor()
}

func (ExecuteMode) Type() protoreflect.EnumType {
	return &file_message_schema_proto_enumTypes[0]
}

func (x ExecuteMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecuteMode.Descriptor instead.
func (ExecuteMode) EnumDescriptor() ([]byte, []int) {
	return file_message_schema_proto_rawDescGZIP(), []int{0}
}

type DefaultMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Ref1          string                 `protobuf:"bytes,2,opt,name=ref1,proto3" json:"ref1,omitempty"`   //client reference
	Ref2          string                 `protobuf:"bytes,3,opt,name=ref2,proto3" json:"ref2,omitempty"`   //message reference
	Ref3          string                 `protobuf:"bytes,4,opt,name=ref3,proto3" json:"ref3,omitempty"`   //end-user reference
	Owner         string                 `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"` //service reference
	PublishedBy   string                 `protobuf:"bytes,6,opt,name=publishedBy,proto3" json:"publishedBy,omitempty"`
	PublishedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=publishedAt,proto3" json:"publishedAt,omitempty"`
	Feature       string                 `protobuf:"bytes,8,opt,name=feature,proto3" json:"feature,omitempty"`
	Data          []byte                 `protobuf:"bytes,9,opt,name=data,proto3" json:"data,omitempty"`  //attachment
	Type          string                 `protobuf:"bytes,10,opt,name=type,proto3" json:"type,omitempty"` //message type eg. reply message, notification
	ExcuteMode    ExecuteMode            `protobuf:"varint,11,opt,name=excuteMode,proto3,enum=messagechema.ExecuteMode" json:"excuteMode,omitempty"`
	CallbackTopic string                 `protobuf:"bytes,12,opt,name=callbackTopic,proto3" json:"callbackTopic,omitempty"`
	Error         string                 `protobuf:"bytes,13,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DefaultMessage) Reset() {
	*x = DefaultMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_schema_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultMessage) ProtoMessage() {}

func (x *DefaultMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_schema_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultMessage.ProtoReflect.Descriptor instead.
func (*DefaultMessage) Descriptor() ([]byte, []int) {
	return file_message_schema_proto_rawDescGZIP(), []int{0}
}

func (x *DefaultMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DefaultMessage) GetRef1() string {
	if x != nil {
		return x.Ref1
	}
	return ""
}

func (x *DefaultMessage) GetRef2() string {
	if x != nil {
		return x.Ref2
	}
	return ""
}

func (x *DefaultMessage) GetRef3() string {
	if x != nil {
		return x.Ref3
	}
	return ""
}

func (x *DefaultMessage) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *DefaultMessage) GetPublishedBy() string {
	if x != nil {
		return x.PublishedBy
	}
	return ""
}

func (x *DefaultMessage) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *DefaultMessage) GetFeature() string {
	if x != nil {
		return x.Feature
	}
	return ""
}

func (x *DefaultMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DefaultMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DefaultMessage) GetExcuteMode() ExecuteMode {
	if x != nil {
		return x.ExcuteMode
	}
	return ExecuteMode_Asynchronous
}

func (x *DefaultMessage) GetCallbackTopic() string {
	if x != nil {
		return x.CallbackTopic
	}
	return ""
}

func (x *DefaultMessage) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HealthCheckMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Feature     string        `protobuf:"bytes,1,opt,name=feature,proto3" json:"feature,omitempty"`
	Description string        `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ExecuteMode []ExecuteMode `protobuf:"varint,3,rep,packed,name=executeMode,proto3,enum=messagechema.ExecuteMode" json:"executeMode,omitempty"`
	ServiceName string        `protobuf:"bytes,4,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
}

func (x *HealthCheckMessage) Reset() {
	*x = HealthCheckMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_schema_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthCheckMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckMessage) ProtoMessage() {}

func (x *HealthCheckMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_schema_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckMessage.ProtoReflect.Descriptor instead.
func (*HealthCheckMessage) Descriptor() ([]byte, []int) {
	return file_message_schema_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckMessage) GetFeature() string {
	if x != nil {
		return x.Feature
	}
	return ""
}

func (x *HealthCheckMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *HealthCheckMessage) GetExecuteMode() []ExecuteMode {
	if x != nil {
		return x.ExecuteMode
	}
	return nil
}

func (x *HealthCheckMessage) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

var File_message_schema_proto protoreflect.FileDescriptor

var file_message_schema_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2d, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x95, 0x03, 0x0a, 0x0e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x66, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x72, 0x65, 0x66, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x66, 0x32, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x65, 0x66, 0x32, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x65,
	0x66, 0x33, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x65, 0x66, 0x33, 0x12, 0x14,
	0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f,
	0x77, 0x6e, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65,
	0x64, 0x42, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x65, 0x64, 0x42, 0x79, 0x12, 0x3c, 0x0a, 0x0b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x65, 0x64, 0x41, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x65, 0x78, 0x63, 0x75, 0x74, 0x65,
	0x4d, 0x6f, 0x64, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x65, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x0a, 0x65, 0x78, 0x63, 0x75, 0x74, 0x65, 0x4d, 0x6f, 0x64,
	0x65, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x54, 0x6f, 0x70,
	0x69, 0x63, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61,
	0x63, 0x6b, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xaf, 0x01,
	0x0a, 0x12, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x3b, 0x0a, 0x0b, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65,
	0x52, 0x0b, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x2a,
	0x30, 0x0a, 0x0b, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x10,
	0x0a, 0x0c, 0x41, 0x73, 0x79, 0x6e, 0x63, 0x68, 0x72, 0x6f, 0x6e, 0x6f, 0x75, 0x73, 0x10, 0x00,
	0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x79, 0x6e, 0x63, 0x68, 0x72, 0x6f, 0x6e, 0x6f, 0x75, 0x73, 0x10,
	0x01, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x3b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_schema_proto_rawDescOnce sync.Once
	file_message_schema_proto_rawDescData = file_message_schema_proto_rawDesc
)

func file_message_schema_proto_rawDescGZIP() []byte {
	file_message_schema_proto_rawDescOnce.Do(func() {
		file_message_schema_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_schema_proto_rawDescData)
	})
	return file_message_schema_proto_rawDescData
}

var file_message_schema_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_message_schema_proto_goTypes = []interface{}{
	(ExecuteMode)(0),              // 0: messagechema.ExecuteMode
	(*DefaultMessage)(nil),        // 1: messagechema.DefaultMessage
	(*HealthCheckMessage)(nil),    // 2: messagechema.HealthCheckMessage
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_message_schema_proto_depIdxs = []int32{
	3, // 0: messagechema.DefaultMessage.publishedAt:type_name -> google.protobuf.Timestamp
	0, // 1: messagechema.DefaultMessage.excuteMode:type_name -> messagechema.ExecuteMode
	0, // 2: messagechema.HealthCheckMessage.executeMode:type_name -> messagechema.ExecuteMode
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_message_schema_proto_init() }
func file_message_schema_proto_init() {
	if File_message_schema_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_schema_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_schema_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthCheckMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_schema_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_schema_proto_goTypes,
		DependencyIndexes: file_message_schema_proto_depIdxs,
		EnumInfos:         file_message_schema_proto_enumTypes,
		MessageInfos:      file_message_schema_proto_msgTypes,
	}.Build()
	File_message_schema_proto = out.File
	file_message_schema_proto_rawDesc = nil
	file_message_schema_proto_goTypes = nil
	file_message_schema_proto_depIdxs = nil
}
