apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: planxnx
  uid: 66636bad-b394-4caf-8743-7ac6055e5bfe
  labels:
    app: service
spec:
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  selector:
    app: api-gateway